name: Mon premier workflow

on:
  push:
    branches:
      - '*'

env:
  MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Mon job simple
        run: echo "Mon premier workflow sur Github Actions"
      - name: Définir une variable dans les "vars"
        run: echo "Ca ne fonctionne pas ==> ::set-var name=MA_VAR::ma-valeur"

  un-autre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Utilisation de la variable "var" dans un autre job
        run: echo ${{ vars.MA_VAR }}

  un-3eme-job:
    runs-on: ubuntu-latest
    steps:
      - name: Utilisation de la variable "var" dans un autre job
        run: echo "Le token est : ${{ env.MY_SECRET_TOKEN }}"
