    name: Get Project Version
    on:
      push:
        branches:
          - master
     
    jobs:
      get-version:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
     
          # Ajoutez ici les étapes nécessaires pour récupérer la version du projet
          - name: Get project version
            id: get-version
            run: echo "name=version::$(node -p "require('./package.json').version")" >> GITHUB_OUTPUT
 
          - name: Show project version
            run: echo "The project version is ${{ steps.get-version.outputs.version }}"
